site_name: SharePoint App Registration and Token Handling
site_description: Documentation on setting up Azure AD app, permissions, and using certificates for SharePoint.
nav:
  - Home: index.md
  - Azure App Registration: azure_app_registration.md
  - Permissions Required: permissions.md
  - Certificate Authentication: certificate_auth.md
theme:
  name: material
  feature:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      Primary: teal
      accent: lime

markdown_extensions:
   - pymdownx.highlight:
       anchor_linenums: true
   - pymdownx.inlinehilite
   - pymdownx.snippets
   - admonition
   - pymdownx.arithmatex:
       generic: true
   - footnotes
   - pymdownx.details
   - pymdownx.superfences
   - attr_list
   - pymdownx.emoji:
       emoji_index: !!python/name:materialx.emoji.twemoji
       emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
   &copy; 2024 <a>Anmol chourasia<a>

